//! Poseidon hash over the BN254 scalar field (circomlib / `maci-crypto` variant).
//!
//! Ported from `circomlibjs/src/poseidon_reference.js`, using the exact round
//! parameters and pre-computed constant tables the reference implementation
//! ships (generated by the HadesHash `generate_parameters_grain.sage` script for
//! the BN254 scalar field). Privacy Pools' TypeScript SDK hashes via
//! `maci-crypto`, which is circomlib-compatible, so these are the hashes the
//! on-chain contracts and the withdrawal circuit expect.
//!
//! Only the three arities the protocol needs are exposed:
//!   * `hash1`  — width t=2  (1 input)
//!   * `hash2`  — width t=3  (2 inputs): precommitment, LeanIMT node, master keys
//!   * `hash3`  — width t=4  (3 inputs): commitment = hash(value, label, precommitment)

use alloy_primitives::U256;

use crate::field::{FIELD_P, add, from_hex, mul, pow5, reduce};
use crate::poseidon_constants::{T2_C, T2_M, T3_C, T3_M, T4_C, T4_M};

const N_ROUNDS_F: usize = 8;
const N_ROUNDS_P: &[usize] = &[
    56, 57, 56, 60, 60, 63, 64, 63, 60, 66, 60, 65, 70, 60, 64, 68,
];

struct Params {
    t: usize,
    n_rounds_p: usize,
    c: Vec<U256>,
    m: Vec<Vec<U256>>,
}

impl Params {
    fn build(t: usize, c_raw: &[&str], m_raw: &[&[&str]]) -> Self {
        let n_rounds_p = N_ROUNDS_P[t - 2];
        let c = c_raw
            .iter()
            .map(|s| from_hex(s).expect("poseidon constant"))
            .collect::<Vec<_>>();
        debug_assert_eq!(c.len(), (N_ROUNDS_F + n_rounds_p) * t);
        let m = m_raw
            .iter()
            .map(|row| {
                row.iter()
                    .map(|s| from_hex(s).expect("mds"))
                    .collect::<Vec<_>>()
            })
            .collect::<Vec<_>>();
        debug_assert_eq!(m.len(), t);
        Params {
            t,
            n_rounds_p,
            c,
            m,
        }
    }
}

fn perm(params: &Params, inputs: &[U256]) -> U256 {
    debug_assert_eq!(inputs.len() + 1, params.t);
    let mut state: Vec<U256> = Vec::with_capacity(params.t);
    state.push(U256::ZERO); // initState = 0
    for &x in inputs {
        state.push(reduce(x));
    }

    let total = N_ROUNDS_F + params.n_rounds_p;
    let half = N_ROUNDS_F / 2; // 4
    for r in 0..total {
        // ark: add round constants
        let base = r * params.t;
        for (i, cell) in state.iter_mut().enumerate() {
            *cell = add(*cell, params.c[base + i]);
        }
        // s-box
        if r < half || r >= half + params.n_rounds_p {
            for cell in state.iter_mut() {
                *cell = pow5(*cell);
            }
        } else {
            state[0] = pow5(state[0]);
        }
        // mix: new[i] = Σ_j M[i][j] * state[j]
        let mut new_state = vec![U256::ZERO; params.t];
        for (i, slot) in new_state.iter_mut().enumerate() {
            let mut acc = U256::ZERO;
            let row = &params.m[i];
            for (j, &value) in state.iter().enumerate() {
                acc = add(acc, mul(row[j], value));
            }
            *slot = acc;
        }
        state = new_state;
    }
    state[0]
}

fn params_t2() -> &'static Params {
    static P: std::sync::OnceLock<Params> = std::sync::OnceLock::new();
    P.get_or_init(|| Params::build(2, T2_C, T2_M))
}
fn params_t3() -> &'static Params {
    static P: std::sync::OnceLock<Params> = std::sync::OnceLock::new();
    P.get_or_init(|| Params::build(3, T3_C, T3_M))
}
fn params_t4() -> &'static Params {
    static P: std::sync::OnceLock<Params> = std::sync::OnceLock::new();
    P.get_or_init(|| Params::build(4, T4_C, T4_M))
}

/// Poseidon over a single input (width t=2).
pub fn hash1(x: U256) -> U256 {
    perm(params_t2(), &[reduce(x)])
}

/// Poseidon over two inputs (width t=3). Used for precommitments and LeanIMT
/// internal nodes: `poseidon([a, b])`.
pub fn hash2(a: U256, b: U256) -> U256 {
    perm(params_t3(), &[reduce(a), reduce(b)])
}

/// Poseidon over three inputs (width t=4). Used for commitments:
/// `poseidon([value, label, precommitment])`.
pub fn hash3(a: U256, b: U256, c: U256) -> U256 {
    perm(params_t4(), &[reduce(a), reduce(b), reduce(c)])
}

/// True if `x` is a valid field element (`x < p`).
pub fn in_field(x: U256) -> bool {
    x < FIELD_P
}

#[cfg(test)]
mod tests {
    use super::*;

    fn hex(s: &str) -> U256 {
        from_hex(s).unwrap()
    }

    /// Reference vector from circomlibjs `test/poseidon.js`:
    /// `poseidonperm_x5_254_3`, i.e. width t=3 (2 inputs).
    #[test]
    fn vector_two_inputs() {
        let got = hash2(hex("0x1"), hex("0x2"));
        let want = hex("0x115cc0f5e7d690413df64c6b9662e9cf2a3617f2743245519e19607a4417189a");
        assert_eq!(got, want);
    }

    /// Reference vectors for width t=4 (3 inputs), pinned against an
    /// independent oracle run of `circomlibjs@0.1.7` (the canonical reference
    /// implementation this file ports). Oracle script:
    /// `goal-privacy-pools/oracle/run.js`; raw output captured in
    /// `goal-privacy-pools/oracle/oracle-output.json`. circomlibjs's published
    /// test suite has no 3-input vector, so the oracle run is the authority.
    #[test]
    fn vector_three_inputs() {
        assert_eq!(
            hash3(hex("0x1"), hex("0x2"), hex("0x3")),
            hex("0x0e7732d89e6939c0ff03d5e58dab6302f3230e269dc5b968f725df34ab36d732")
        );
        assert_eq!(
            hash3(hex("0x5"), hex("0x6"), hex("0x7")),
            hex("0x0ad5e51d5e2b51072b4f16472824a3aa88af65d84c564461ead109c9037a2696")
        );
        assert_eq!(
            hash3(hex("0xa"), hex("0x14"), hex("0x1e")),
            hex("0x09724f5ed614c216f9b30cdd8b70bbabd81459ded9e979593a3842379f595f89")
        );
        // hash3(0,0,0) is a legitimate, non-zero field element.
        assert_eq!(
            hash3(U256::ZERO, U256::ZERO, U256::ZERO),
            hex("0x0bc188d27dcceadc1dcfb6af0a7af08fe2864eecec96c5ae7cee6db31ba599aa")
        );
    }

    /// Reference vector: width t=2 (1 input), single output. The decimal value
    /// is the form circomlibjs publishes; cross-checked against the oracle run.
    #[test]
    fn vector_one_input() {
        let got = hash1(hex("0x1"));
        let want_dec =
            "18586133768512220936620570745912940619677854269274689475585506675881198879027";
        assert_eq!(got.to_string(), want_dec);
    }

    #[test]
    fn deterministic_and_field_reduced() {
        let a = hash2(U256::from(7), U256::from(9));
        let b = hash2(U256::from(7), U256::from(9));
        assert_eq!(a, b);
        assert!(in_field(a));
        assert_ne!(a, U256::ZERO);
    }

    #[test]
    fn reduces_above_modulus_inputs() {
        // Inputs above the field modulus are reduced first; the result must be
        // identical to hashing the reduced value.
        let big = FIELD_P + U256::from(5);
        let got = hash1(big);
        let want = hash1(U256::from(5));
        assert_eq!(got, want);
    }
}
